### PR TITLE
Erreur

### PR DESCRIPTION
**Pull request by emmas2210**
The adjective utter should be used instead of the adverb utterly.

### CODE REVIEW

**Review by josephsalmon — CHANGES_REQUESTED** [review]
"It is from the utterly importance to implement tests" still non correct a sentence. A better formulation is needed.

**Comment by emmas2210** [comment]
I'd suggest : 
It's why we place utter most importance  in implement tests.

**Comment by josephsalmon** [comment]
It's why we place utter most importanc**ing** in implement tests.
?

**Comment by emmas2210** [comment]
Yes that's better.

**Comment by josephsalmon** [comment]
so can you edit your PR to reflect that? thx.

**Pull request closed without merging**
